#!/bin/sh
#
# Mount points from /etc/fstab

set -e

mount_overlay ()
{
    src=$1
    dst=/tmp$1

    cp -dR $src /tmp/
    /bin/mount $src
    mv $dst/* $src/
    rmdir $dst
}

/bin/mount /proc
/bin/mount /sys
/bin/mount /tmp

#mount -o remount,ro /
mount_overlay /var
mount_overlay /dev

